package commands

import (
	"fmt"

	"github.com/gkarolyi/mxt/internal/ui"
)

// HelpCommand prints the help output matching mxt.
func HelpCommand(version string) {
	printLogo(version)
	fmt.Println()
	fmt.Println()

	fmt.Printf("%sUSAGE%s\n", ui.Bold, ui.Reset)
	fmt.Println("    mxt <command> [options]")
	fmt.Println()

	fmt.Printf("%sCOMMANDS%s\n", ui.Bold, ui.Reset)
	fmt.Printf("    %sinit%s                              Set up global config (~/.mxt/config)\n", ui.Cyan, ui.Reset)
	fmt.Println("        --local                       Create project config (.mxt in repo root)")
	fmt.Println("        --reinit                      Overwrite existing config without prompting")
	fmt.Printf("    %sconfig%s                            Show current config (global + project)\n", ui.Cyan, ui.Reset)
	fmt.Println()
	fmt.Println("        Terminal options: terminal, iterm2, ghostty, current")
	fmt.Println("        - terminal: macOS Terminal.app (new window)")
	fmt.Println("        - iterm2: iTerm2 (new window)")
	fmt.Println("        - ghostty: Ghostty (new tab via 'open -a')")
	fmt.Println("        - current: Attach in currently active terminal (any app)")
	fmt.Println()
	fmt.Printf("    %snew%s [branch] [options]             Create worktree + tmux session\n", ui.Cyan, ui.Reset)
	fmt.Println("        (prompts for branch when omitted)")
	fmt.Println("        --from <branch>               Base branch (default: main/master)")
	fmt.Println("        --run <claude|codex>          Auto-run command in agent window")
	fmt.Println("        --bg                          Create session without opening terminal")
	fmt.Println()
	fmt.Printf("    %slist%s                              List worktrees, diff stats, session status\n", ui.Cyan, ui.Reset)
	fmt.Println()
	fmt.Printf("    %sdelete%s <branch> [--force]          Delete worktree and branch (with confirmation)\n", ui.Cyan, ui.Reset)
	fmt.Println()
	fmt.Printf("    %ssessions%s <action> <branch> [opts]  Manage tmux session for a worktree\n", ui.Cyan, ui.Reset)
	fmt.Println("        open   <branch> [--run cmd]   Create session & open terminal")
	fmt.Println("        close  <branch>               Kill tmux session")
	fmt.Println("        relaunch <branch> [--run cmd] Close + reopen session")
	fmt.Println("        attach <branch> [dev|agent]   Attach to session (optionally select window)")
	fmt.Println()
	fmt.Printf("    %shelp%s                              Show this help message\n", ui.Cyan, ui.Reset)
	fmt.Println()
	fmt.Printf("%sEXAMPLES%s\n", ui.Bold, ui.Reset)
	fmt.Println("    mxt init                          # Global setup")
	fmt.Println("    mxt init --local                  # Project-specific copy_files")
	fmt.Println("    mxt init --reinit                 # Overwrite existing config")
	fmt.Println("    mxt new                          # Prompt for branch name")
	fmt.Println("    mxt new feature-auth              # New worktree from main")
	fmt.Println("    mxt new fix-bug --from develop    # New worktree from develop")
	fmt.Println("    mxt new feature-ai --run claude   # Auto-launch claude code")
	fmt.Println("    mxt new fix-bug --bg              # Create without opening terminals")
	fmt.Println("    mxt list                          # Show all worktrees + status")
	fmt.Println("    mxt sessions close feature-auth   # Kill tmux sessions")
	fmt.Println("    mxt sessions relaunch fix-bug     # Restart sessions")
	fmt.Println("    mxt delete feature-auth           # Remove worktree + branch")
	fmt.Println()
	fmt.Printf("%sCONFIG%s\n", ui.Bold, ui.Reset)
	fmt.Println("    Global:  ~/.mxt/config")
	fmt.Println("             (worktree_dir, terminal, copy_files, pre_session_cmd, tmux_layout)")
	fmt.Println("    Project: .mxt in repo root      (overrides global settings)")
	fmt.Println("    Env:     MXT_CONFIG_DIR=/path    (override global config dir)")
	fmt.Println()
	fmt.Printf("    %sHooks & Layout:%s\n", ui.Bold, ui.Reset)
	fmt.Println("    - pre_session_cmd:  Runs after worktree setup, before tmux session")
	fmt.Println("                        Good for: bundle install, npm install, db:migrate")
	fmt.Println()
	fmt.Println("    - tmux_layout:      Define custom tmux windows and panes")
	fmt.Println("                        Multi-line format (recommended):")
	fmt.Println("                        tmux_layout=[")
	fmt.Println("                          dev:hx|lazygit")
	fmt.Println("                          server:cd api && bin/server|cd ui && yarn start")
	fmt.Println("                          logs:tail -f log/development.log")
	fmt.Println("                          agent:")
	fmt.Println("                        ]")
	fmt.Println()
	fmt.Println("                        Single-line format: dev:hx|lazygit,server:bin/server,agent:")
	fmt.Println()
	fmt.Println("                        Syntax:")
	fmt.Println("                        - ',' or newline separates windows")
	fmt.Println("                        - ':' separates window name from panes")
	fmt.Println("                        - '|' separates panes (vertical split - side by side)")
	fmt.Println("                        - Empty command = shell prompt")
	fmt.Println()
	fmt.Println("                        If not set, creates default: dev + agent windows")
	fmt.Println()
}

func printLogo(version string) {
	fmt.Println("                       _")
	fmt.Println("  _ __ ___  _   ___  _| |_ _ __ ___  ___")
	fmt.Println(" | '_ ` _ \\| | | \\ \\/ / __| '__/ _ \\/ _ \\")
	fmt.Println(" | | | | | | |_| |>  <| |_| | |  __/  __/")
	fmt.Println(" |_| |_| |_|\\__,_/_/\\_\\\\__|_|  \\___|\\___|")
	fmt.Println(ui.DimText(fmt.Sprintf("  Tmux Worktree Session Manager v%s", version)))
}
